//! Persistent regional railway news and development history.
//!
//! The Bulletin intentionally contains significant world developments rather
//! than routine Train movements. It is a read-only view over persisted events
//! generated by simulation systems such as the Rail Authority lifecycle.

mod dashboard;
mod detail;
mod filter_bar;
mod format;
mod header;
mod layout;
mod log;

use crossterm::event::KeyCode;
use ratatui::{Frame, layout::Rect, widgets::TableState};

use crate::model::{BulletinCategory, BulletinEntry, GameState, UtcSeconds};

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum BulletinFilter {
    #[default]
    All,
    Local,
    Authority,
    Construction,
    Network,
}

impl BulletinFilter {
    fn next(self) -> Self {
        match self {
            Self::All => Self::Local,
            Self::Local => Self::Authority,
            Self::Authority => Self::Construction,
            Self::Construction => Self::Network,
            Self::Network => Self::All,
        }
    }

    pub(super) const fn label(self) -> &'static str {
        match self {
            Self::All => "All",
            Self::Local => "Local",
            Self::Authority => "Authority",
            Self::Construction => "Construction",
            Self::Network => "Network",
        }
    }

    pub(super) const fn matches(self, category: BulletinCategory) -> bool {
        match self {
            Self::All => true,
            Self::Local => matches!(category, BulletinCategory::Local),
            Self::Authority => matches!(category, BulletinCategory::Authority),
            Self::Construction => matches!(category, BulletinCategory::Construction),
            Self::Network => matches!(category, BulletinCategory::Network),
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct BulletinShortcut {
    pub key: String,
    pub action: String,
    pub enabled: bool,
}

impl BulletinShortcut {
    fn enabled(key: impl Into<String>, action: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            action: action.into(),
            enabled: true,
        }
    }

    fn disabled(key: impl Into<String>, action: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            action: action.into(),
            enabled: false,
        }
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct BulletinWorkspace {
    filter: BulletinFilter,
    table_state: TableState,
    page_size: usize,
    visit_seen_count: Option<u64>,
}

impl BulletinWorkspace {
    /// Starts one Bulletin visit and returns the current entry count when new
    /// developments need to be durably acknowledged.
    pub fn begin_visit(&mut self, state: &GameState) -> Option<u64> {
        let total = bulletin_count(state);
        let seen = state.bulletin_seen_count.min(total);
        self.visit_seen_count = Some(seen);
        (total > seen).then_some(total)
    }

    pub(super) fn visit_seen_count(&self, state: &GameState) -> u64 {
        self.visit_seen_count
            .unwrap_or(state.bulletin_seen_count)
            .min(bulletin_count(state))
    }

    pub fn handle_key(&mut self, key: KeyCode, state: &GameState) {
        if matches!(key, KeyCode::Char('f' | 'F')) {
            self.filter = self.filter.next();
            self.table_state.select(Some(0));
            *self.table_state.offset_mut() = 0;
            self.synchronize(state);
            return;
        }

        self.synchronize(state);
        let count = visible_entries(state, self.filter).len();
        let Some(selected) = self.table_state.selected() else {
            return;
        };
        let page_size = self.page_size.max(1);
        let next = match key {
            KeyCode::Up | KeyCode::Char('k' | 'K') => selected.saturating_sub(1),
            KeyCode::Down | KeyCode::Char('j' | 'J') => {
                selected.saturating_add(1).min(count.saturating_sub(1))
            }
            KeyCode::PageUp => selected.saturating_sub(page_size),
            KeyCode::PageDown => selected
                .saturating_add(page_size)
                .min(count.saturating_sub(1)),
            _ => selected,
        };
        self.table_state.select((count > 0).then_some(next));
    }

    pub fn render(&mut self, frame: &mut Frame, area: Rect, state: &GameState, now: UtcSeconds) {
        dashboard::render(frame, area, state, now, self);
    }

    /// Returns the contextual footer actions for the Bulletin workspace.
    pub fn shortcuts(
        &mut self,
        state: &GameState,
        compact: bool,
        wide: bool,
    ) -> Vec<BulletinShortcut> {
        self.synchronize(state);
        let visible_count = visible_entries(state, self.filter).len();
        let development = if visible_count == 0 {
            BulletinShortcut::disabled(
                if compact { "↑↓" } else { "↑↓/JK" },
                "Development",
            )
        } else {
            BulletinShortcut::enabled(
                if compact { "↑↓" } else { "↑↓/JK" },
                "Development",
            )
        };
        let mut items = vec![development];
        if wide && self.has_multiple_pages(state) {
            items.push(BulletinShortcut::enabled("PgUp/PgDn", "Page"));
        }
        items.push(BulletinShortcut::enabled(
            "F",
            format!("View · {}", self.filter_label()),
        ));
        items
    }

    /// Returns help content for the Bulletin workspace.
    pub fn help_lines(&self) -> Vec<String> {
        vec![
            "Current · Railway Bulletin".into(),
            "↑↓ / jk Select development".into(),
            "PgUp / PgDn Page through the development log".into(),
            "f Cycle view: All / Local / Authority / Construction / Network".into(),
            String::new(),
            "The Bulletin records significant world developments, not routine Train movements."
                .into(),
        ]
    }

    pub const fn filter_label(&self) -> &'static str {
        self.filter.label()
    }

    pub(super) fn filter(&self) -> BulletinFilter {
        self.filter
    }

    pub(super) fn table_state_mut(&mut self) -> &mut TableState {
        &mut self.table_state
    }

    pub(super) fn set_page_size(&mut self, page_size: usize) {
        self.page_size = page_size;
    }

    fn has_multiple_pages(&self, state: &GameState) -> bool {
        self.page_size >= 2 && visible_entries(state, self.filter).len() > self.page_size
    }

    pub(super) fn synchronize(&mut self, state: &GameState) {
        let count = visible_entries(state, self.filter).len();
        if count == 0 {
            self.table_state.select(None);
            *self.table_state.offset_mut() = 0;
            return;
        }
        let selected = self.table_state.selected().unwrap_or(0).min(count - 1);
        self.table_state.select(Some(selected));
    }
}

pub(super) fn bulletin_count(state: &GameState) -> u64 {
    u64::try_from(state.region.bulletin.len()).unwrap_or(u64::MAX)
}

pub(super) fn unread_count(state: &GameState) -> u64 {
    let total = bulletin_count(state);
    total.saturating_sub(state.bulletin_seen_count.min(total))
}

pub(super) fn visible_entries(
    state: &GameState,
    filter: BulletinFilter,
) -> Vec<(usize, &BulletinEntry)> {
    state
        .region
        .bulletin
        .iter()
        .enumerate()
        .rev()
        .filter(|(_, entry)| filter.matches(entry.category))
        .collect()
}

#[cfg(test)]
mod tests {
    use crate::{
        model::{BulletinCategory, BulletinEntry, UtcSeconds},
        sim::world::create_new_game,
    };

    use super::{BulletinFilter, visible_entries};

    #[test]
    fn newest_matching_items_are_shown_first() {
        let mut state = create_new_game(7, "One More Prime", UtcSeconds::from_unix_seconds(1));
        state.region.bulletin = vec![
            BulletinEntry {
                occurred_at: UtcSeconds::from_unix_seconds(10),
                category: BulletinCategory::Local,
                headline: "First".into(),
                detail: "First detail".into(),
            },
            BulletinEntry {
                occurred_at: UtcSeconds::from_unix_seconds(20),
                category: BulletinCategory::Authority,
                headline: "Second".into(),
                detail: "Second detail".into(),
            },
        ];

        let all = visible_entries(&state, BulletinFilter::All);
        assert_eq!(all[0].1.headline, "Second");
        assert_eq!(all[1].1.headline, "First");
        let local = visible_entries(&state, BulletinFilter::Local);
        assert_eq!(local.len(), 1);
        assert_eq!(local[0].1.headline, "First");
    }
}
