//! Persistent regional railway news and development history.
//!
//! The Bulletin intentionally contains significant world developments rather
//! than routine Train movements. It is a read-only view over persisted events
//! generated by simulation systems such as the Rail Authority lifecycle.

use crossterm::event::KeyCode;
use ratatui::{
    Frame,
    layout::{Constraint, Layout, Rect},
    style::Style,
    text::{Line, Span},
    widgets::{Cell, HighlightSpacing, Paragraph, Row, Table, TableState, Wrap},
};

use crate::{
    model::{BulletinCategory, BulletinEntry, GameState, UtcSeconds},
    ui::{components::panel_block, theme},
};

#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum BulletinFilter {
    #[default]
    All,
    Local,
    Authority,
    Construction,
    Network,
}

impl BulletinFilter {
    fn next(self) -> Self {
        match self {
            Self::All => Self::Local,
            Self::Local => Self::Authority,
            Self::Authority => Self::Construction,
            Self::Construction => Self::Network,
            Self::Network => Self::All,
        }
    }

    const fn label(self) -> &'static str {
        match self {
            Self::All => "All",
            Self::Local => "Local",
            Self::Authority => "Authority",
            Self::Construction => "Construction",
            Self::Network => "Network",
        }
    }

    const fn matches(self, category: BulletinCategory) -> bool {
        match self {
            Self::All => true,
            Self::Local => matches!(category, BulletinCategory::Local),
            Self::Authority => matches!(category, BulletinCategory::Authority),
            Self::Construction => matches!(category, BulletinCategory::Construction),
            Self::Network => matches!(category, BulletinCategory::Network),
        }
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct BulletinWorkspace {
    filter: BulletinFilter,
    table_state: TableState,
    page_size: usize,
}

impl BulletinWorkspace {
    pub fn handle_key(&mut self, key: KeyCode, state: &GameState) {
        if matches!(key, KeyCode::Char('f' | 'F')) {
            self.filter = self.filter.next();
            self.table_state.select(Some(0));
            *self.table_state.offset_mut() = 0;
            self.synchronize(state);
            return;
        }

        self.synchronize(state);
        let count = visible_entries(state, self.filter).len();
        let Some(selected) = self.table_state.selected() else {
            return;
        };
        let page_size = self.page_size.max(1);
        let next = match key {
            KeyCode::Up | KeyCode::Char('k' | 'K') => selected.saturating_sub(1),
            KeyCode::Down | KeyCode::Char('j' | 'J') => {
                selected.saturating_add(1).min(count.saturating_sub(1))
            }
            KeyCode::PageUp => selected.saturating_sub(page_size),
            KeyCode::PageDown => selected
                .saturating_add(page_size)
                .min(count.saturating_sub(1)),
            _ => selected,
        };
        self.table_state.select((count > 0).then_some(next));
    }

    pub fn render(&mut self, frame: &mut Frame, area: Rect, state: &GameState, now: UtcSeconds) {
        if area.height < 12 {
            frame.render_widget(
                Paragraph::new("Railway Bulletin\n\nOpen this workspace in a taller terminal to inspect regional developments.")
                    .block(panel_block("Bulletin", false))
                    .style(theme::panel())
                    .wrap(Wrap { trim: true }),
                area,
            );
            return;
        }

        let [summary_area, list_area, detail_area] = Layout::vertical([
            Constraint::Length(4),
            Constraint::Length((area.height / 2).max(7)),
            Constraint::Fill(1),
        ])
        .areas(area);

        self.render_summary(frame, summary_area, state, now);
        self.render_list(frame, list_area, state, now);
        self.render_detail(frame, detail_area, state, now);
    }

    pub const fn filter_label(&self) -> &'static str {
        self.filter.label()
    }

    fn synchronize(&mut self, state: &GameState) {
        let count = visible_entries(state, self.filter).len();
        if count == 0 {
            self.table_state.select(None);
            *self.table_state.offset_mut() = 0;
            return;
        }
        let selected = self.table_state.selected().unwrap_or(0).min(count - 1);
        self.table_state.select(Some(selected));
    }

    fn render_summary(&self, frame: &mut Frame, area: Rect, state: &GameState, now: UtcSeconds) {
        let entries = visible_entries(state, self.filter);
        let visible = entries.len();
        let total = state.region.bulletin.len();
        let latest = entries
            .first()
            .map(|(_, entry)| relative_time(entry.occurred_at, now))
            .unwrap_or_else(|| "—".into());
        let lines = vec![
            Line::from(vec![
                Span::styled("History  ", theme::secondary()),
                Span::styled(format!("{total} recorded"), theme::primary_value()),
                Span::styled(format!(" · {visible} shown"), theme::secondary()),
            ]),
            Line::from(vec![
                Span::styled("View  ", theme::secondary()),
                Span::styled(self.filter.label(), theme::focused_title()),
                Span::styled(" · Latest  ", theme::secondary()),
                Span::styled(latest, theme::primary_value()),
            ]),
        ];
        frame.render_widget(
            Paragraph::new(lines)
                .block(panel_block("Railway Bulletin", false))
                .style(theme::panel()),
            area,
        );
    }

    fn render_list(&mut self, frame: &mut Frame, area: Rect, state: &GameState, now: UtcSeconds) {
        let entries = visible_entries(state, self.filter);
        if entries.is_empty() {
            frame.render_widget(
                Paragraph::new(vec![
                    Line::styled("No Bulletin items in this category yet.", theme::secondary()),
                    Line::styled(
                        "Significant council, Authority, construction, and network events will appear here.",
                        theme::secondary(),
                    ),
                ])
                .block(panel_block("Latest Developments", false))
                .style(theme::panel())
                .wrap(Wrap { trim: true }),
                area,
            );
            self.table_state.select(None);
            return;
        }

        self.page_size = usize::from(area.height.saturating_sub(3)).max(1);
        self.synchronize(state);
        let rows = entries
            .iter()
            .map(|(_, entry)| {
                Row::new(vec![
                    Cell::from(relative_time(entry.occurred_at, now)),
                    Cell::from(category_label(entry.category))
                        .style(category_style(entry.category)),
                    Cell::from(entry.headline.clone()),
                ])
            })
            .collect::<Vec<_>>();
        let table = Table::new(
            rows,
            [
                Constraint::Length(10),
                Constraint::Length(14),
                Constraint::Fill(1),
            ],
        )
        .header(Row::new(["When", "Type", "Development"]).style(theme::table_header()))
        .block(panel_block("Latest Developments", false))
        .row_highlight_style(theme::selected_row())
        .highlight_symbol(theme::SELECTION_MARKER)
        .highlight_spacing(HighlightSpacing::Always);
        frame.render_stateful_widget(table, area, &mut self.table_state);
    }

    fn render_detail(&mut self, frame: &mut Frame, area: Rect, state: &GameState, now: UtcSeconds) {
        self.synchronize(state);
        let entries = visible_entries(state, self.filter);
        let selected = self
            .table_state
            .selected()
            .and_then(|index| entries.get(index));
        let Some((_, entry)) = selected else {
            frame.render_widget(
                Paragraph::new("No development selected.")
                    .block(panel_block("Development", false))
                    .style(theme::panel()),
                area,
            );
            return;
        };

        let lines = vec![
            Line::from(vec![
                Span::styled(
                    category_label(entry.category),
                    category_style(entry.category),
                ),
                Span::styled(
                    format!("  ·  {}", relative_time(entry.occurred_at, now)),
                    theme::secondary(),
                ),
            ]),
            Line::from(""),
            Line::styled(entry.headline.clone(), theme::title()),
            Line::from(""),
            Line::styled(entry.detail.clone(), theme::primary_value()),
        ];
        frame.render_widget(
            Paragraph::new(lines)
                .block(panel_block("Development", false))
                .style(theme::panel())
                .wrap(Wrap { trim: true }),
            area,
        );
    }
}

fn visible_entries(state: &GameState, filter: BulletinFilter) -> Vec<(usize, &BulletinEntry)> {
    state
        .region
        .bulletin
        .iter()
        .enumerate()
        .rev()
        .filter(|(_, entry)| filter.matches(entry.category))
        .collect()
}

fn category_label(category: BulletinCategory) -> &'static str {
    match category {
        BulletinCategory::Local => "LOCAL",
        BulletinCategory::Authority => "AUTHORITY",
        BulletinCategory::Construction => "CONSTRUCTION",
        BulletinCategory::Network => "NETWORK",
    }
}

fn category_style(category: BulletinCategory) -> Style {
    match category {
        BulletinCategory::Local => theme::primary_value(),
        BulletinCategory::Authority => theme::focused_title(),
        BulletinCategory::Construction => theme::warning(),
        BulletinCategory::Network => theme::success(),
    }
}

fn relative_time(timestamp: UtcSeconds, now: UtcSeconds) -> String {
    let seconds = now
        .unix_seconds()
        .saturating_sub(timestamp.unix_seconds())
        .max(0) as u64;
    if seconds < 60 {
        "now".into()
    } else if seconds < 3_600 {
        format!("{}m ago", seconds / 60)
    } else if seconds < 86_400 {
        format!("{}h ago", seconds / 3_600)
    } else {
        format!("{}d ago", seconds / 86_400)
    }
}

#[cfg(test)]
mod tests {
    use crate::{
        model::{BulletinCategory, BulletinEntry, UtcSeconds},
        sim::world::create_new_game,
    };

    use super::{BulletinFilter, visible_entries};

    #[test]
    fn newest_matching_items_are_shown_first() {
        let mut state = create_new_game(7, "One More Prime", UtcSeconds::from_unix_seconds(1));
        state.region.bulletin = vec![
            BulletinEntry {
                occurred_at: UtcSeconds::from_unix_seconds(10),
                category: BulletinCategory::Local,
                headline: "First".into(),
                detail: "First detail".into(),
            },
            BulletinEntry {
                occurred_at: UtcSeconds::from_unix_seconds(20),
                category: BulletinCategory::Authority,
                headline: "Second".into(),
                detail: "Second detail".into(),
            },
        ];

        let all = visible_entries(&state, BulletinFilter::All);
        assert_eq!(all[0].1.headline, "Second");
        assert_eq!(all[1].1.headline, "First");
        let local = visible_entries(&state, BulletinFilter::Local);
        assert_eq!(local.len(), 1);
        assert_eq!(local[0].1.headline, "First");
    }
}
